# Generated by Django 4.1.3 on 2022-11-07 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lat', models.DecimalField(blank=True, decimal_places=16, help_text='location latitude Driver', max_digits=22, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=16, help_text='location longitude Driver', max_digits=22, null=True)),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DriverRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 11, 7, 18, 24, 11, 226108, tzinfo=datetime.timezone.utc))),
                ('response', models.JSONField()),
            ],
        ),
    ]
