# Generated by Django 4.1.3 on 2022-11-09 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lat', models.PositiveIntegerField(help_text='location latitude Driver', validators=[django.core.validators.MaxValueValidator(100)])),
                ('lng', models.PositiveIntegerField(help_text='location longitude Driver', validators=[django.core.validators.MaxValueValidator(100)])),
                ('last_update', models.DateTimeField()),
            ],
        ),
    ]
