# Generated by Django 4.1.3 on 2022-11-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lat', models.DecimalField(blank=True, decimal_places=16, help_text='location latitude Driver', max_digits=22, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=16, help_text='location longitude Driver', max_digits=22, null=True)),
                ('last_update', models.DateTimeField()),
            ],
        ),
    ]
