# Generated by Django 4.1.3 on 2022-11-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_driverrequestlog_creation_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverRequestLog',
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
