# Generated by Django 4.1.3 on 2022-11-10 03:33

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 11, 10, 3, 33, 18, 231260, tzinfo=datetime.timezone.utc))),
                ('order_date', models.DateTimeField()),
                ('lat_origin', models.PositiveIntegerField(help_text='location latitude origin order', validators=[django.core.validators.MaxValueValidator(100)])),
                ('lng_origin', models.PositiveIntegerField(help_text='location longitude origin order', validators=[django.core.validators.MaxValueValidator(100)])),
                ('lat_destination', models.PositiveIntegerField(help_text='location latitude destination order', validators=[django.core.validators.MaxValueValidator(100)])),
                ('lng_destination', models.PositiveIntegerField(help_text='location longitude destination order', validators=[django.core.validators.MaxValueValidator(100)])),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
    ]
