# Generated by Django 4.1.3 on 2022-11-09 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 9, 22, 6, 52, 312191, tzinfo=datetime.timezone.utc)),
        ),
    ]
