# Generated by Django 4.1.3 on 2022-11-09 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 9, 23, 36, 3, 289840, tzinfo=datetime.timezone.utc)),
        ),
    ]
