# Generated by Django 4.1.3 on 2022-11-10 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 10, 0, 13, 11, 541311, tzinfo=datetime.timezone.utc)),
        ),
    ]
